{% set version = "0.9.2" %}

package:
  name: "pdgraster"
  version: {{ version }}

source:
  url: https://github.com/PermafrostDiscoveryGateway/viz-raster/archive/{{ version }}.tar.gz
  sha256: eb8ca23c2c8f794b88c1a680cc1a671d5d722093c33bb142f5fecd5f2be43e4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - __unix  # [unix]
    - python >={{ python_min }},<4.0
    - numpy >=1.2
    - shapely >=2,<3.0
    - geopandas >=0.12.2,<1.0
    - morecantile >=3.1,<4.0
    - rtree >=0.9,<1.0
    - coloraide >=0.10,<1
    - colormaps ==0.4.0
    - pillow >=9,<10
    - rasterio >=1.2,<2
    - pydantic 1.10.9
    - pdgstaging

test:
  imports:
    - pdgraster
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PermafrostDiscoveryGateway/viz-raster
  license: Apache-2.0
  license_file: LICENSE
  summary: Permafrost Discovery Gateway vizualization pipeline for raster processing

extra:
  recipe-maintainers:
    - mfisher87
    - rushirajnenuji
