{% set version = "0.9.3" %}

package:
  name: "pdgraster"
  version: {{ version }}

source:
  url: https://github.com/PermafrostDiscoveryGateway/viz-raster/archive/{{ version }}.tar.gz
  sha256: c7ec3ad742cce777be2c1584f52ae2447a59ffd89f87aa69ec1fd65af5872a71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - __unix  # [unix]
    - python >=3.9,<4.0
    - numpy >=1.2
    - shapely >=2,<3.0
    - geopandas >=0.12.2,<1.0
    - morecantile >=3.1,<4.0
    - rtree >=0.9,<1.0
    - coloraide >=0.10,<1
    - colormaps ==0.4.0
    - pillow >=9,<10
    - rasterio >=1.2,<2
    - pydantic 1.10.9
    - pdgstaging

test:
  imports:
    - pdgraster
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PermafrostDiscoveryGateway/viz-raster
  license: Apache-2.0
  license_file: LICENSE
  summary: Permafrost Discovery Gateway vizualization pipeline for raster processing

extra:
  recipe-maintainers:
    - mfisher87
    - rushirajnenuji
